### ISSUE TITLE
WKT parsing affected by locale of decimal formatting 

### ISSUE THREAD

**Issue by alexgao1** [GCRC/nunaliit#1061]
On simplification of geometries, the WKT string produced may not be the expected typical value if on a different locale. This results in a document/feature that won't save or process fully.

**Comment by ahayes** [comment]
Specifically, choosing a locale that uses commas as decimal points in numbers results in creation of nunaliit_geom wkt strings in an invalid format. e.g. `POINT(12,3456 78,9012)`

**Comment by thiagogomesverissimo** [comment]
This is a log from Nunaliit running in an Ubuntu Desktop version installed in portuguese and therefore with commas as decimal points:

```
2022-08-08 16:45:34,386[ERROR]: Error processing document 54c58d598f3d7c3c1d79f4cfb1145e11 (simplifyGeometry)                                                                        
java.lang.Exception: Error parsing WKT string: MULTIPOINT((-46,70876 -23,5538))                                                                                                      
        at ca.carleton.gcrc.geom.wkt.WktParser.parseWkt(WktParser.java:29)                                                                                                           
        at ca.carleton.gcrc.couch.onUpload.conversion.GeometryDescriptor.setGeometryAsWkt(GeometryDescriptor.java:56)                                                                
        at ca.carleton.gcrc.couch.onUpload.simplifyGeoms.GeometrySimplifierImpl.simplifyGeometry(GeometrySimplifierImpl.java:133)                                                    
        at ca.carleton.gcrc.couch.onUpload.UploadWorkerThread.performSimplifyGeometryWork(UploadWorkerThread.java:792)                                                               
        at ca.carleton.gcrc.couch.onUpload.UploadWorkerThread.performWork(UploadWorkerThread.java:264)                                                                               
        at ca.carleton.gcrc.couch.onUpload.UploadWorkerThread.activity(UploadWorkerThread.java:161)                                                                                  
        at ca.carleton.gcrc.couch.onUpload.UploadWorkerThread.run(UploadWorkerThread.java:132) 
```

**Comment by thiagogomesverissimo** [comment]
Hi,

I built from `1061/locale-decimal-formatting` branch and now this log disappeared. 

Thanks a lot.
