### ISSUE TITLE
Build error: Cannot find parent: org.apache.geronimo.genesis.config:config

### ISSUE THREAD

**Issue by drobilla** [GCRC/nunaliit#329]
Doing a "mvn install" as per the developer documentation:

```
$ mvn --version
Apache Maven 2.2.1 (rdebian-17)
Java version: 1.7.0_79
Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
Default locale: en_CA, platform encoding: UTF-8
OS name: "linux" version: "3.14-2-rt-amd64" arch: "amd64" Family: "unix"
```

```
$ mvn install
[INFO] Scanning for projects...
[INFO] Reactor build order: 
[INFO]   nunaliit2
[INFO]   nunaliit2-jdbc
[INFO]   nunaliit2-json
[INFO]   nunaliit2-jdbc-json
[INFO]   nunaliit2-search
[INFO]   nunaliit2-auth-common
[INFO]   nunaliit2-auth-cookie
[INFO]   nunaliit2-dbSec
[INFO]   nunaliit2-auth-http
[INFO]   nunaliit2-dbWeb
[INFO]   nunaliit2-adhocQueries
[INFO]   nunaliit2-contributions
[INFO]   nunaliit2-multimedia
[INFO]   nunaliit2-progress
[INFO]   nunaliit2-upload
[INFO]   nunaliit2-onUpload
[INFO]   nunaliit2-javascript
[INFO]   nunaliit2-css
[INFO]   nunaliit2-js-external
[INFO]   nunaliit2-js
[INFO]   nunaliit2-utils
[INFO]   nunaliit2-war-relations
[INFO]   nunaliit2-atlas-relations
[INFO]   nunaliit2-security
[INFO]   nunaliit2-couch-client
[INFO]   nunaliit2-couch-replication
[INFO]   nunaliit2-gpx-jaxb
[INFO]   nunaliit2-gpx
[INFO]   nunaliit2-mail
[INFO]   nunaliit2-couch-utils
[INFO]   nunaliit2-geom
[INFO]   nunaliit2-couch-user
[INFO]   nunaliit2-couch-onUpload
[INFO]   nunaliit2-couch-export
[INFO]   nunaliit2-couch-config
[INFO]   nunaliit2-couch-application
[INFO]   nunaliit2-couch-mobile
[INFO]   nunaliit2-couch-submission
[INFO]   nunaliit2-couch-date
[INFO]   nunaliit2-couch-command
[INFO]   nunaliit2-couch-sdk
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).


Project ID: null:project-config:pom:1.1

Reason: Cannot find parent: org.apache.geronimo.genesis.config:config for project: null:project-config:pom:1.1 for project null:project-config:pom:1.1


[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1 second
[INFO] Finished at: Wed May 20 23:15:55 EDT 2015
[INFO] Final Memory: 7M/118M
[INFO] ------------------------------------------------------------------------
```

Debug output:

```
$ mvn install -e
+ Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] Reactor build order: 
[INFO]   nunaliit2
[INFO]   nunaliit2-jdbc
[INFO]   nunaliit2-json
[INFO]   nunaliit2-jdbc-json
[INFO]   nunaliit2-search
[INFO]   nunaliit2-auth-common
[INFO]   nunaliit2-auth-cookie
[INFO]   nunaliit2-dbSec
[INFO]   nunaliit2-auth-http
[INFO]   nunaliit2-dbWeb
[INFO]   nunaliit2-adhocQueries
[INFO]   nunaliit2-contributions
[INFO]   nunaliit2-multimedia
[INFO]   nunaliit2-progress
[INFO]   nunaliit2-upload
[INFO]   nunaliit2-onUpload
[INFO]   nunaliit2-javascript
[INFO]   nunaliit2-css
[INFO]   nunaliit2-js-external
[INFO]   nunaliit2-js
[INFO]   nunaliit2-utils
[INFO]   nunaliit2-war-relations
[INFO]   nunaliit2-atlas-relations
[INFO]   nunaliit2-security
[INFO]   nunaliit2-couch-client
[INFO]   nunaliit2-couch-replication
[INFO]   nunaliit2-gpx-jaxb
[INFO]   nunaliit2-gpx
[INFO]   nunaliit2-mail
[INFO]   nunaliit2-couch-utils
[INFO]   nunaliit2-geom
[INFO]   nunaliit2-couch-user
[INFO]   nunaliit2-couch-onUpload
[INFO]   nunaliit2-couch-export
[INFO]   nunaliit2-couch-config
[INFO]   nunaliit2-couch-application
[INFO]   nunaliit2-couch-mobile
[INFO]   nunaliit2-couch-submission
[INFO]   nunaliit2-couch-date
[INFO]   nunaliit2-couch-command
[INFO]   nunaliit2-couch-sdk
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).


Project ID: null:project-config:pom:1.1

Reason: Cannot find parent: org.apache.geronimo.genesis.config:config for project: null:project-config:pom:1.1 for project null:project-config:pom:1.1


[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Unable to get dependency information: Unable to read the metadata file for artifact 'org.apache.geronimo.specs:geronimo-j2ee-deployment_1.1_spec:jar': Cannot find parent: org.apache.geronimo.genesis.config:config for project: null:project-config:pom:1.1 for project null:project-config:pom:1.1
  org.apache.geronimo.specs:geronimo-j2ee-deployment_1.1_spec:jar:1.1

from the specified remote repositories:
  central (https://repo1.maven.org/maven2),
  sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots),
  codehaus-snapshots (http://nexus.codehaus.org/snapshots/)

Path to dependency: 
	1) org.codehaus.cargo:cargo-maven2-plugin:maven-plugin:1.2.4
	2) org.codehaus.cargo:cargo-core-api-generic:jar:1.2.4
	3) org.codehaus.cargo:cargo-core-api-container:jar:1.2.4


	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.loadPluginFully(DefaultLifecycleExecutor.java:1607)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.findArtifactTypeHandlersInPlugins(DefaultLifecycleExecutor.java:1468)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.findExtensions(DefaultLifecycleExecutor.java:222)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:178)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
	at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
	at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
	at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.artifact.resolver.ArtifactResolutionException: Unable to get dependency information: Unable to read the metadata file for artifact 'org.apache.geronimo.specs:geronimo-j2ee-deployment_1.1_spec:jar': Cannot find parent: org.apache.geronimo.genesis.config:config for project: null:project-config:pom:1.1 for project null:project-config:pom:1.1
  org.apache.geronimo.specs:geronimo-j2ee-deployment_1.1_spec:jar:1.1

from the specified remote repositories:
  central (https://repo1.maven.org/maven2),
  sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots),
  codehaus-snapshots (http://nexus.codehaus.org/snapshots/)

Path to dependency: 
	1) org.codehaus.cargo:cargo-maven2-plugin:maven-plugin:1.2.4
	2) org.codehaus.cargo:cargo-core-api-generic:jar:1.2.4
	3) org.codehaus.cargo:cargo-core-api-container:jar:1.2.4


	at org.apache.maven.artifact.resolver.DefaultArtifactCollector.recurse(DefaultArtifactCollector.java:430)
	at org.apache.maven.artifact.resolver.DefaultArtifactCollector.recurse(DefaultArtifactCollector.java:435)
	at org.apache.maven.artifact.resolver.DefaultArtifactCollector.recurse(DefaultArtifactCollector.java:435)
	at org.apache.maven.artifact.resolver.DefaultArtifactCollector.collect(DefaultArtifactCollector.java:74)
	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:316)
	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:304)
	at org.apache.maven.plugin.DefaultPluginManager.ensurePluginContainerIsComplete(DefaultPluginManager.java:835)
	at org.apache.maven.plugin.DefaultPluginManager.loadPluginFully(DefaultPluginManager.java:1629)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.loadPluginFully(DefaultLifecycleExecutor.java:1582)
	... 15 more
Caused by: org.apache.maven.artifact.metadata.ArtifactMetadataRetrievalException: Unable to read the metadata file for artifact 'org.apache.geronimo.specs:geronimo-j2ee-deployment_1.1_spec:jar': Cannot find parent: org.apache.geronimo.genesis.config:config for project: null:project-config:pom:1.1 for project null:project-config:pom:1.1
	at org.apache.maven.project.artifact.MavenMetadataSource.retrieveRelocatedProject(MavenMetadataSource.java:200)
	at org.apache.maven.project.artifact.MavenMetadataSource.retrieveRelocatedArtifact(MavenMetadataSource.java:94)
	at org.apache.maven.artifact.resolver.DefaultArtifactCollector.recurse(DefaultArtifactCollector.java:387)
	... 23 more
Caused by: org.apache.maven.project.ProjectBuildingException: Cannot find parent: org.apache.geronimo.genesis.config:config for project: null:project-config:pom:1.1 for project null:project-config:pom:1.1
	at org.apache.maven.project.DefaultMavenProjectBuilder.assembleLineage(DefaultMavenProjectBuilder.java:1396)
	at org.apache.maven.project.DefaultMavenProjectBuilder.assembleLineage(DefaultMavenProjectBuilder.java:1407)
	at org.apache.maven.project.DefaultMavenProjectBuilder.assembleLineage(DefaultMavenProjectBuilder.java:1407)
	at org.apache.maven.project.DefaultMavenProjectBuilder.buildInternal(DefaultMavenProjectBuilder.java:823)
	at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromRepository(DefaultMavenProjectBuilder.java:255)
	at org.apache.maven.project.artifact.MavenMetadataSource.retrieveRelocatedProject(MavenMetadataSource.java:163)
	... 25 more
Caused by: org.apache.maven.project.InvalidProjectModelException: Not a v4.0.0 POM. for project org.apache.geronimo.genesis.config:config at /home/drobilla/.m2/repository/org/apache/geronimo/genesis/config/config/1.1/config-1.1.pom
	at org.apache.maven.project.DefaultMavenProjectBuilder.readModel(DefaultMavenProjectBuilder.java:1599)
	at org.apache.maven.project.DefaultMavenProjectBuilder.readModel(DefaultMavenProjectBuilder.java:1571)
	at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:562)
	at org.apache.maven.project.DefaultMavenProjectBuilder.assembleLineage(DefaultMavenProjectBuilder.java:1392)
	... 30 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1 second
[INFO] Finished at: Wed May 20 23:09:04 EDT 2015
[INFO] Final Memory: 7M/149M
[INFO] ------------------------------------------------------------------------
```

Apologies if this is obvious, never used Maven before...

**Comment by ahayes** [comment]
I had a compile problem recently too. It was due to someone removing project binaries from maven's online repository (which I thought was never supposed to happen). This looks very similar.

**Comment by drobilla** [comment]
Yep, looks to be the case.  Judging by the web, others have had this problem for the same package on different projects.

**Comment by ahayes** [comment]
I wonder if apache's maven repo is having trouble syncing with central. Apache's repo for the troublesome dependancy is here:

https://repository.apache.org/content/repositories/releases/org/apache/geronimo/genesis/

JP should be able to sort this out once he jumps in.

**Comment by jpfiset** [comment]
I wiped my Maven cached repository and attempted to reproduce the problem. However, it built successfully.

It could have been a temporary failure of the central repository. Or, we are not compiling the same version of Nunaliit.

I tested on the latest on the master branch.

Would you mind trying again? If you encounter the issue again, can you let me know which version of Nunaliit you are trying to build?

**Comment by drobilla** [comment]
latest master.

I wiped my cache and it now works successfully, too, thanks.  Strange, since I had no maven cache at all when I started.  I suppose the repository was broken somehow at that point and maven wasn't smart enough to update something.
