### ISSUE TITLE
Upload error reported with insufficient information

### ISSUE THREAD

**Issue by jpfiset** [GCRC/nunaliit#355]
A document is left in an unexpected state after a failure of loading a document.

````
docId: 3cedafd41b6a52dadec103bf8a06e0ab
uploadId: 3cedafd41b6a52dadec103bf8a06ea9b

2015-07-14 16:52:30,491[INFO ]: UploadServlet >welcome<
2015-07-14 16:52:37,830[INFO ]: ProgressServlet getIds
2015-07-14 16:52:37,999[INFO ]: ProgressServlet getProgresses
2015-07-14 16:52:38,378[INFO ]: UploadServlet >put<
2015-07-14 16:52:38,378[INFO ]: Upload progressId:progress20
2015-07-14 16:52:38,379[INFO ]: Upload uploadId:3cedafd41b6a52dadec103bf8a06ea9b
2015-07-14 16:52:38,379[INFO ]: Upload file is The Midway Lake Music Festival.pd
f
2015-07-14 16:52:39,323[INFO ]: ProgressServlet getProgresses
2015-07-14 16:52:42,257[INFO ]: ProgressServlet getProgresses
2015-07-14 16:52:43,767[INFO ]: ProgressServlet getProgresses
2015-07-14 16:52:45,591[INFO ]: ProgressServlet getProgresses
2015-07-14 16:52:47,562[INFO ]: ProgressServlet getProgresses
2015-07-14 16:52:49,205[INFO ]: ProgressServlet getProgresses
2015-07-14 16:52:50,822[INFO ]: ProgressServlet getProgresses
2015-07-14 16:52:52,809[INFO ]: ProgressServlet getProgresses
2015-07-14 16:52:54,837[INFO ]: ProgressServlet getProgresses
2015-07-14 16:52:56,637[INFO ]: ProgressServlet getProgresses
2015-07-14 16:52:58,616[INFO ]: ProgressServlet getProgresses
2015-07-14 16:53:01,315[INFO ]: ProgressServlet getProgresses
2015-07-14 16:53:03,451[INFO ]: ProgressServlet getProgresses
2015-07-14 16:53:05,502[INFO ]: ProgressServlet getProgresses
2015-07-14 16:53:07,599[INFO ]: ProgressServlet getProgresses
2015-07-14 16:53:09,566[INFO ]: ProgressServlet getProgresses
2015-07-14 16:53:11,421[INFO ]: ProgressServlet getProgresses
2015-07-14 16:53:14,717[INFO ]: ProgressServlet getProgresses
2015-07-14 16:53:16,181[INFO ]: ProgressServlet getProgresses
2015-07-14 16:53:17,427[INFO ]: ProgressServlet getProgresses
2015-07-14 16:53:18,086[INFO ]: Error loading file <unknown>
java.lang.Exception: Error while writing file /home/nunaliit/gwichin/./media/upl9076609051383812085.pdf
        at ca.carleton.gcrc.upload.UploadServlet.doFileUpload(UploadServlet.java:321)
        at ca.carleton.gcrc.upload.UploadServlet.doPost(UploadServlet.java:224)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539)
        at java.lang.Thread.run(Thread.java:745)
````

The first issue is that not enough information is provided by the raised exception.

When the document is displayed, a note reports that the attachment is being processed. However, this is the state of the document:

````json
{
   "_id": "3cedafd41b6a52dadec103bf8a06e0ab",
   "_rev": "1-9d439f4d4ac4f9b945f81edb548ac5c5",
   "nunaliit_type": "gwichin_media",
   "nunaliit_attachments": {
       "files": {
           "media": {
               "status": "waiting for upload",
               "uploadId": "3cedafd41b6a52dadec103bf8a06ea9b",
               "data": {
               },
               "attachmentName": "media"
           }
       },
       "nunaliit_type": "attachment_descriptions"
   },
   "nunaliit_source": {
       "category": "attachment",
       "nunaliit_type": "reference",
       "doc": "gwichin.placename.1159"
   },
   "nunaliit_schema": "gwichin_media",
}

````

**Comment by jpfiset** [comment]
````
2015-07-29 14:18:11,812[INFO ]: UploadServlet >put<
2015-07-29 14:18:11,813[INFO ]: Upload progressId:progress0
2015-07-29 14:18:11,813[INFO ]: Upload uploadId:3cedafd41b6a52dadec103bf8a0f860c
2015-07-29 14:18:11,814[INFO ]: Upload file is The Midway Lake Music Festival.pd
f
2015-07-29 14:18:48,511[INFO ]: Error loading file <unknown>
java.lang.Exception: Error while writing file /home/nunaliit/gwichin/./media/upl
7714260020752920711.pdf
        at ca.carleton.gcrc.upload.UploadServlet.doFileUpload(UploadServlet.java:321)
        at ca.carleton.gcrc.upload.UploadServlet.doPost(UploadServlet.java:224)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.jetty.io.EofException: Early EOF
        at org.eclipse.jetty.server.HttpInput$3.noContent(HttpInput.java:486)
        at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:124)
        at org.apache.commons.fileupload.MultipartStream$ItemInputStream.makeAvailable(MultipartStream.java:977)
        at org.apache.commons.fileupload.MultipartStream$ItemInputStream.read(MultipartStream.java:857)
        at ca.carleton.gcrc.upload.UploadServlet.doFileUpload(UploadServlet.java:318)
        ... 19 more
````

**Comment by jpfiset** [comment]
I have tracked down the problem. As it happens, this is a network issue. The network connection appears to be lost during the upload. When connection issues are experienced, the probability of encountering this issue increases with the size of the uploaded file.

From a Nunaliit perspective, there are two issues:
1. When an upload does not complete, the user is not informed properly that the file was not uploaded.
2. On the server side, documents that were created to accommodate the upload are not cleaned up. Therefore, the user is left with documents that report attachments that will never be satisfied.

**Comment by ahayes** [comment]
Eilan, we'll need to talk about this one to decide on an implementation. But better error handling for users during/after failed uploads or processing is something we need.
