### ISSUE TITLE
OGG mime type change (Ubuntu 16.04?) causing build test to fail

### ISSUE THREAD

**Issue by ahayes** [GCRC/nunaliit#532]
Test set: ca.carleton.gcrc.olkit.multimedia.file.SystemFileTest

Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.009 sec <<< FAILURE! - in >ca.carleton.gcrc.olkit.multimedia.file.SystemFileTest
testOgg(ca.carleton.gcrc.olkit.multimedia.file.SystemFileTest) Time elapsed: 0.004 sec <<< >FAILURE!
junit.framework.AssertionFailedError: Unexpected type. Expected: application/ogg Returned: >audio/ogg
at junit.framework.Assert.fail(Assert.java:47)
at ca.carleton.gcrc.olkit.multimedia.file.SystemFileTest.performFile(SystemFileTest.java:53)
at ca.carleton.gcrc.olkit.multimedia.file.SystemFileTest.testOgg(SystemFileTest.java:72)

**Comment by ahayes** [comment]
Fixed by https://github.com/GCRC/nunaliit/commit/97850ea7698b4ecb407bbd2a14029e47b2cf185b
