### ISSUE TITLE
.m4a file processing failure

### ISSUE THREAD

**Issue by cmcneave** [GCRC/nunaliit#696]
Hello.  I have some audio files in .m4a format that are not getting processed by Nunaliit 2.2.9-SNAPSHOT.  The files are stuck with the "Attachment is being processed" message.  These audio files were created using voice recorder app on a Samsung S4 smartphone and the native voice recorder app.

Command line file conversion on the server succeeds with:
$avconv -i Voice211_sd.m4a voicer211.mp3

avconv version information is:

$ avconv -format
avconv version 9.20-6:9.20-0ubuntu0.14.04.1, Copyright (c) 2000-2014 the Libav developers
  built on Dec  7 2016 21:22:31 with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
avconv 9.20-6:9.20-0ubuntu0.14.04.1
libavutil     52.  3. 0 / 52.  3. 0
libavcodec    54. 35. 1 / 54. 35. 1
libavformat   54. 20. 4 / 54. 20. 4
libavdevice   53.  2. 0 / 53.  2. 0
libavfilter    3.  3. 0 /  3.  3. 0
libavresample  1.  0. 1 /  1.  0. 1
libswscale     2.  1. 1 /  2.  1. 1

**Comment by pulsifer** [comment]
Relevant log information will follow momentarily.

**Comment by pulsifer** [comment]
Also note that this has been tested on a number of Nunaliit atlases with the same result.

**Comment by pulsifer** [comment]
This is the type of log activity being reported:

2017-11-01 17:04:51,766[INFO ]: ProgressServlet getProgresses
2017-11-01 17:04:53,272[INFO ]: ProgressServlet getProgresses
2017-11-01 17:04:53,809[INFO ]: UploadServlet >put<
2017-11-01 17:04:53,809[INFO ]: Upload progressId:progress381
2017-11-01 17:04:53,809[INFO ]: Upload uploadId:69b219cee8e74385d9223a8dcc2609b0
2017-11-01 17:04:53,809[INFO ]: Upload file is voice211_sd.m4a
2017-11-01 17:04:53,885[INFO ]: File written to /apps/nunaliit/atlases/staging/yupik/./media/upl1923101749535343036.m4a
2017-11-01 17:04:53,977[INFO ]: onLoad update: 69b219cee8e74385d9223a8dcc267e9d -> [voice211_sd.m4a]
2017-11-01 17:04:53,978[INFO ]: Upload worker processing: Document Work(state:waiting for upload id:69b219cee8e74385d9223a8dcc25fbf0 up
loadId:69b219cee8e74385d9223a8dcc2609b0 uploadRequestDocId:69b219cee8e74385d9223a8dcc267e9d)
2017-11-01 17:04:54,169[INFO ]: Upload worker completed: Document Work(state:waiting for upload id:69b219cee8e74385d9223a8dcc25fbf0 upl
oadId:69b219cee8e74385d9223a8dcc2609b0 uploadRequestDocId:69b219cee8e74385d9223a8dcc267e9d)
2017-11-01 17:04:54,225[INFO ]: Upload worker processing: Document Work(state:submitted id:69b219cee8e74385d9223a8dcc25fbf0 att:voice21
1_sd.m4a)
2017-11-01 17:04:54,337[INFO ]: Upload worker completed: Document Work(state:submitted id:69b219cee8e74385d9223a8dcc25fbf0 att:voice211
_sd.m4a)
2017-11-01 17:04:54,393[INFO ]: Upload worker processing: Document Work(state:analyzed id:69b219cee8e74385d9223a8dcc25fbf0 att:voice211
_sd.m4a)
2017-11-01 17:04:54,473[ERROR]: Unable to obtain submitter information
2017-11-01 17:04:54,517[ERROR]: Unable to obtain submitter information
2017-11-01 17:04:54,560[ERROR]: Error processing document 69b219cee8e74385d9223a8dcc25fbf0 (analyzed)
java.lang.NullPointerException
        at ca.carleton.gcrc.olkit.multimedia.converter.impl.MultimediaConverterImpl.convertVideo(MultimediaConverterImpl.java:74)
        at ca.carleton.gcrc.couch.onUpload.multimedia.MultimediaFileConverter.analyzeFile(MultimediaFileConverter.java:216)
        at ca.carleton.gcrc.couch.onUpload.multimedia.MultimediaFileConverter.performWork(MultimediaFileConverter.java:182)
        at ca.carleton.gcrc.couch.onUpload.UploadWorkerThread.performAnalyzedWork(UploadWorkerThread.java:491)
        at ca.carleton.gcrc.couch.onUpload.UploadWorkerThread.performWork(UploadWorkerThread.java:231)
        at ca.carleton.gcrc.couch.onUpload.UploadWorkerThread.activity(UploadWorkerThread.java:152)
        at ca.carleton.gcrc.couch.onUpload.UploadWorkerThread.run(UploadWorkerThread.java:123)

**Comment by pulsifer** [comment]
Note that uploading the same file in .MP3 format does not cause issues.

**Comment by pulsifer** [comment]
Also note, that I attempted to upload the m4a to a nunaliit atlas on a 16-04 server with the very latest SNAPSHOT of Nunallit.  In this case, it did not stall in processing, however it simply did not recognize the file as an audio file.  It seemed to process it, but provided a download link, no player action/icon etc.. So, I am suspecting that the issue is with the particular format and not the specific instance of Nunaliit.  As you will have seen, we have tried it with different files from different Samsung phones and experienced the same issue.

**Comment by billingb** [comment]
I'm looking into this issue now. It appears to me that the problem is the .m4a file not being recognized as an audio mimetype. I'm going to see if I can add the file type to the recognized file types.

**Comment by pulsifer** [comment]
This makes sense.  In keeping with my comment above, one of the atlases used to test does upload and process the file, but not as an audio file.

**Comment by jpfiset** [comment]
On Ubuntu 16.04, the magic information should be stored in a file under /usr/share/misc/magic. In our case, it should be /usr/share/misc/magic/nunaliit

**Comment by ahayes** [comment]
Actually, /etc/magic still works fine on Ubuntu 16.04. Have you tried the alternative and should we change our docs?
