### ISSUE TITLE
Nunaliit server fails to recover from Premature EOF in changes stream

### ISSUE THREAD

**Issue by ahayes** [GCRC/nunaliit#702]
This error took down a Nunaliit instance. Appears to be related to a system update restarting couchdb.

```
2017-11-23 00:00:00,015[INFO ]: No daily vetter notifications required - nothing waiting for approval
2017-11-23 04:00:00,999[ERROR]: Error accessing database changes
java.io.IOException: Premature EOF
        at sun.net.www.http.ChunkedInputStream.readAheadBlocking(ChunkedInputStream.java:565)
        at sun.net.www.http.ChunkedInputStream.readAhead(ChunkedInputStream.java:609)
        at sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:696)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3375)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at sun.nio.cs.StreamDecoder.read0(StreamDecoder.java:127)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:112)
        at java.io.InputStreamReader.read(InputStreamReader.java:168)
        at ca.carleton.gcrc.couch.client.impl.ConnectionUtils.getJsonFromInputStream(ConnectionUtils.java:32)
        at ca.carleton.gcrc.couch.client.impl.ConnectionUtils.getJsonFromInputStream(ConnectionUtils.java:43)
        at ca.carleton.gcrc.couch.client.impl.ConnectionUtils.getJsonResource(ConnectionUtils.java:104)
        at ca.carleton.gcrc.couch.client.impl.ConnectionUtils.getJsonResource(ConnectionUtils.java:112)
        at ca.carleton.gcrc.couch.client.impl.CouchDbChangeMonitorThread.getChanges(CouchDbChangeMonitorThread.java:113)
        at ca.carleton.gcrc.couch.client.impl.CouchDbChangeMonitorThread.activity(CouchDbChangeMonitorThread.java:81)
        at ca.carleton.gcrc.couch.client.impl.CouchDbChangeMonitorThread.run(CouchDbChangeMonitorThread.java:71)
```

**Comment by ahayes** [comment]
Actually... It looks like Nunaliit may have been started before couchdb on an automatic reboot. Hard to tell from logs. Either way, it would be nice if it retried to connect to couchdb for a few minutes or longer with progressively longer waits between retries.

**Comment by ahayes** [comment]
Looking into this more, it may have been another case of an older startup script trying to start the wrong version of Nunaliit, possibly out of order. I will close and watch for anything similar in other hosts.
