### ISSUE TITLE
Problem in re-processing media when attachment name needs to be modified

### ISSUE THREAD

**Issue by jpfiset** [GCRC/nunaliit#715]
````
2018-01-18 16:00:30,666[INFO ]: Upload worker processing: Document Work(state:analyzed id:bf2d9ec0a9e4b7d52f7879dc12d95c79 att:converted)

2018-01-18 16:00:30,836[ERROR]: Error processing document bf2d9ec0a9e4b7d52f7879dc12d95c79 (analyzed)

java.lang.Exception: Error while performing multimedia file analysis

	at ca.carleton.gcrc.couch.onUpload.multimedia.MultimediaFileConverter.analyzeFile(MultimediaFileConverter.java:470)

	at ca.carleton.gcrc.couch.onUpload.multimedia.MultimediaFileConverter.performWork(MultimediaFileConverter.java:194)

	at ca.carleton.gcrc.couch.onUpload.UploadWorkerThread.performAnalyzedWork(UploadWorkerThread.java:533)

	at ca.carleton.gcrc.couch.onUpload.UploadWorkerThread.performWork(UploadWorkerThread.java:236)

	at ca.carleton.gcrc.couch.onUpload.UploadWorkerThread.activity(UploadWorkerThread.java:157)

	at ca.carleton.gcrc.couch.onUpload.UploadWorkerThread.run(UploadWorkerThread.java:128)

Caused by: java.lang.Exception: Can not rename attachment descriptor because file is already attached

	at ca.carleton.gcrc.couch.onUpload.conversion.AttachmentDescriptor.renameAttachmentTo(AttachmentDescriptor.java:91)

	at ca.carleton.gcrc.couch.onUpload.multimedia.MultimediaFileConverter.analyzeFile(MultimediaFileConverter.java:293)

	... 5 more
````

**Comment by jpfiset** [comment]
The changes performed on Nunaliit simply ignore the rename request when a file is already attached. As of CoucnDB 2.0, there is no easy way of renaming a document attachment. The only proposed approach is to download the attachment and reload it.

Given some of the files are very large, it is not practical to rename an attachment by using an in-memory approach such as the inline attachments.

Also, since the newer versions of Nunaliit handle the naming of attachments correctly, the renaming feature is needed only for special cases. This should be addressed by another approach.
