### ISSUE TITLE
upload servlet bottleneck

### ISSUE THREAD

**Issue by ahayes** [GCRC/nunaliit#728]
Uploading a large file using the File Upload facility of a schema can result in long wait times. The client system reports no more than 400 KB/s upload speed even while connected to the server on a 10Gb/s connection. The system does not appear hardware limited by disk. The java process on the system is pegged at 100% CPU during the upload.

**Comment by ahayes** [comment]
In the end, the upload took so long that it appears to have failed. No indication on the client but the logs show the following:
```
2018-03-09 14:05:19,033[INFO ]: ProgressServlet getProgresses
2018-03-09 14:05:20,120[INFO ]: ProgressServlet getProgresses
2018-03-09 14:05:20,963[INFO ]: ProgressServlet getProgresses
2018-03-09 14:05:22,016[INFO ]: ProgressServlet getProgresses
2018-03-09 14:05:22,166[INFO ]: File written to /home/nunaliit/residentialschools/atlas/./media/upl3658906436653670590.mp4
2018-03-09 14:05:22,265[ERROR]: Unable to create an upload request
ca.carleton.gcrc.couch.client.impl.CouchDbException: CouchDB Error (403) forbidden/Database submissions are restricted to users associated with database
	at ca.carleton.gcrc.couch.client.impl.ConnectionUtils.checkResponseForError(ConnectionUtils.java:501)
	at ca.carleton.gcrc.couch.client.impl.ConnectionUtils.putJsonResource(ConnectionUtils.java:136)
	at ca.carleton.gcrc.couch.client.impl.CouchDbImpl.createDocument(CouchDbImpl.java:103)
	at ca.carleton.gcrc.couch.onUpload.UploadListener.onLoad(UploadListener.java:196)
	at ca.carleton.gcrc.upload.UploadServlet.doFileUpload(UploadServlet.java:341)
	at ca.carleton.gcrc.upload.UploadServlet.doPost(UploadServlet.java:224)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
2018-03-09 14:05:22,995[INFO ]: ProgressServlet getProgresses
```

**Comment by ahayes** [comment]
Screenshot from the inspector.
<img width="1567" alt="screen shot 2018-03-09 at 15 40 54" src="https://user-images.githubusercontent.com/1750076/37303860-2de50f86-2606-11e8-8e03-33dffc3c9240.png">
