### ISSUE TITLE
Export fails on timeout for large datasets

### ISSUE THREAD

**Issue by ahayes** [GCRC/nunaliit#750]
Jetty appears to have a 30s idle timeout that can cause exports to fail. Symptoms appear in the Javascript Console as:
```
Failed to load resource: the server responded with a status of 502 (Bad Gateway) export.geojson:1 
```
and in the nunaliit server side logs as:
```
2018-07-12 16:06:02,422[ERROR]: Unable to report error
java.lang.IllegalStateException: Compressed output stream is already assigned.
	at org.eclipse.jetty.servlets.gzip.AbstractCompressedStream.doNotCompress(AbstractCompressedStream.java:283)
	at org.eclipse.jetty.servlets.gzip.CompressedResponseWrapper.noCompression(CompressedResponseWrapper.java:327)
	at org.eclipse.jetty.servlets.gzip.CompressedResponseWrapper.setStatus(CompressedResponseWrapper.java:169)
	at ca.carleton.gcrc.json.servlet.JsonServlet.reportError(JsonServlet.java:45)
	at ca.carleton.gcrc.couch.export.ExportServlet.doPostRecords(ExportServlet.java:416)
	at ca.carleton.gcrc.couch.export.ExportServlet.doPost(ExportServlet.java:107)
```
followed 30s later by:
```
java.io.IOException: java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
```

Which Jetty are we using? Possible cause (if this is a regression):
https://stackoverflow.com/questions/25548341/jetty-idletimeout

**Comment by ahayes** [comment]
Yep. We are using Jetty 9.2 which has the 30s timeout on http requests.

**Comment by ahayes** [comment]
Tried upping the timeout by setting http.setIdleTimeout in the Jetty connector but the error then shifted to being a 504 Gateway Timeout. I then tried setting the Timeout directive in Apache (applies to mod_proxy as well) and I'm still getting a 504 Gateway Timeout error.

**Comment by qrafzv** [comment]
2018-08-08 21:54:00,306[DEBUG]: SelectChannelEndPoint@3a801f96{/0:0:0:0:0:0:0:1:33316<->8080,Open,in,out,-,W,30000/30000,HttpConnection}{io=4,kio=4,kro=1} idle timeout check, elapsed: 30000 ms, remaining: 0 ms
2018-08-08 21:54:00,307[DEBUG]: SelectChannelEndPoint@3a801f96{/0:0:0:0:0:0:0:1:33316<->8080,Open,in,out,-,W,30001/30000,HttpConnection}{io=4,kio=4,kro=1} idle timeout expired
2018-08-08 21:54:00,307[DEBUG]: failed: WriteFlusher@1d26bd77{PENDING} java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
2018-08-08 21:54:00,307[DEBUG]: update WriteFlusher@1d26bd77{IDLE}:PENDING-->IDLE
2018-08-08 21:54:00,307[DEBUG]: Ignored idle endpoint SelectChannelEndPoint@3a801f96{/0:0:0:0:0:0:0:1:33316<->8080,Open,in,out,-,-,30001/30000,HttpConnection}{io=4,kio=4,kro=1}
**2018-08-08 21:54:00,307[DEBUG]: Error in the exporting Record Func
java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms withId: 82aa477e6ab152a1d6016e30c6127d602252a6d8**
2018-08-08 21:54:00,307[DEBUG]: Error exporting record
2018-08-08 21:54:00,307[DEBUG]: Error in ExportFormat 
2018-08-08 21:54:00,309[ERROR]: Unable to report error

Here is the DEBUG info. This connection seems to exceed the "idle timeout" setting in Jetty (30000ms).
I am trying to figure out how to change this configuration in maven-jetty. Any suggestion?

**Comment by qrafzv** [comment]
Another odd thing is that the timeout incident always happen to the same document above (Id: 82aa477e6ab152a1d6016e30c6127d602252a6d8)
Anything weird you guys can spot? 
{
   "type":"Feature",
   "id":"82aa477e6ab152a1d6016e30c6127d602252a6d8",
   "properties":{
      "schema":"ncri_observation",
      "intervieweeNames":"Henry Ohokannoak",
      "notes":"Gravel pit area, where the cabins are.",
      "time_of_year":"",
      "speciesCategory":"Fish",
      "docId":"8a382439cd35d712bf6e9686f8190ebd",
      "interpreterNames":"",
      "flags":"",
      "interviewerIds":"",
      "speciesId":"3f90734745ec4f5991c03961cc1008b3",
      "geometryId":"8a382439cd35d712bf6e9686f8190ebd",
      "intervieweeIds":"d021dd66bbb3c3dca1076732ab0061fb",
      "interpreterIds":"",
      "communityIds":"8a382439cd35d712bf6e9686f84a099b",
      "communityNames":"Cambridge Bay",
      "interviewerNames":"",
      "interviewId":"add39baa232b48e024bc58ec100a2906",
      "speciesName":"Capelin",
      "id":"82aa477e6ab152a1d6016e30c6127d602252a6d8",
      "direction":""
   },
   "geometry":{
      "type":"MultiPolygon",
      "coordinates":[
         [
            [
               [
                  -105.044712479,
                  69.064988051
               ],
               [
                  -105.042335682,
                  69.06838479
               ],
...
