### ISSUE TITLE
Misidentification of some PDF files as audio

### ISSUE THREAD

**Issue by ahayes** [GCRC/nunaliit#770]
Some user submitted PDF files on an atlas we host are being misidentified as audio files and Nunaliit fails while attempting to convert them to MP3. In addition, the failure appears to pollute the media folder with `conv` files.

```
2018-11-16 17:17:12,292[INFO ]: Upload worker processing: Document Work(state:analyzed id:7d9ee21c69c7c85fbf7cf1ea8c2fa427 att:22 77 21 - Schadensstatistiken mit dem Stand vom 1. Mai 1944 - Schnellermittlung_Duisburg.pdf)
2018-11-16 17:17:14,789[INFO ]: Command (avconv -i /home/nunaliit/wardamage/./media/upl6473203729053996903.pdf -y -acodec libmp3lame -ab 48000 -ac 2 -threads 0 -f mp3 /home/nunaliit/wardamage/./media/conv1967304033121386857.mp3) exited with value 1
2018-11-16 17:17:14,791[ERROR]: Error processing document 7d9ee21c69c7c85fbf7cf1ea8c2fa427 (analyzed)
java.lang.Exception: Error while performing multimedia file analysis
	at ca.carleton.gcrc.couch.onUpload.multimedia.MultimediaFileConverter.analyzeFile(MultimediaFileConverter.java:517)
	at ca.carleton.gcrc.couch.onUpload.multimedia.MultimediaFileConverter.performWork(MultimediaFileConverter.java:227)
	at ca.carleton.gcrc.couch.onUpload.UploadWorkerThread.performAnalyzedWork(UploadWorkerThread.java:533)
	at ca.carleton.gcrc.couch.onUpload.UploadWorkerThread.performWork(UploadWorkerThread.java:236)
	at ca.carleton.gcrc.couch.onUpload.UploadWorkerThread.activity(UploadWorkerThread.java:157)
	at ca.carleton.gcrc.couch.onUpload.UploadWorkerThread.run(UploadWorkerThread.java:128)
Caused by: java.lang.Exception: Process exited with value: 1
	at ca.carleton.gcrc.olkit.multimedia.ffmpeg.FFmpegProcessorDefault.convertAudio(FFmpegProcessorDefault.java:204)
	at ca.carleton.gcrc.olkit.multimedia.converter.impl.MultimediaConverterImpl.convertAudio(MultimediaConverterImpl.java:195)
	at ca.carleton.gcrc.couch.onUpload.multimedia.MultimediaFileConverter.analyzeFile(MultimediaFileConverter.java:267)
	... 5 more
2018-11-16 17:17:14,810[INFO ]: Upload worker processing: Document Work(state:analyzed id:7d9ee21c69c7c85fbf7cf1ea8c2fbceb att:22 77 21 - Schadensstatistiken mit dem Stand vom 1. Mai 1944 - Schnellermittlung_Düsseldorf.pdf)
2018-11-16 17:17:15,886[INFO ]: Command (avconv -i /home/nunaliit/wardamage/./media/upl1735288235089807052.pdf -y -acodec libmp3lame -ab 48000 -ac 2 -threads 0 -f mp3 /home/nunaliit/wardamage/./media/conv6569608823794827452.mp3) exited with value 69
2018-11-16 17:17:15,888[ERROR]: Error processing document 7d9ee21c69c7c85fbf7cf1ea8c2fbceb (analyzed)
java.lang.Exception: Error while performing multimedia file analysis
	at ca.carleton.gcrc.couch.onUpload.multimedia.MultimediaFileConverter.analyzeFile(MultimediaFileConverter.java:517)
	at ca.carleton.gcrc.couch.onUpload.multimedia.MultimediaFileConverter.performWork(MultimediaFileConverter.java:227)
	at ca.carleton.gcrc.couch.onUpload.UploadWorkerThread.performAnalyzedWork(UploadWorkerThread.java:533)
	at ca.carleton.gcrc.couch.onUpload.UploadWorkerThread.performWork(UploadWorkerThread.java:236)
	at ca.carleton.gcrc.couch.onUpload.UploadWorkerThread.activity(UploadWorkerThread.java:157)
	at ca.carleton.gcrc.couch.onUpload.UploadWorkerThread.run(UploadWorkerThread.java:128)
Caused by: java.lang.Exception: Process exited with value: 69
	at ca.carleton.gcrc.olkit.multimedia.ffmpeg.FFmpegProcessorDefault.convertAudio(FFmpegProcessorDefault.java:204)
	at ca.carleton.gcrc.olkit.multimedia.converter.impl.MultimediaConverterImpl.convertAudio(MultimediaConverterImpl.java:195)
	at ca.carleton.gcrc.couch.onUpload.multimedia.MultimediaFileConverter.analyzeFile(MultimediaFileConverter.java:267)
	... 5 more
```

**Comment by ahayes** [comment]
@qrafzv discovered that this is a side effect of Issue #769. Because ImageMagick is unable to read the PDF, it gets handed to ffmpeg for identification and things go downhill from there. Unfortunately, updating the policy as a workaround does not fix this issue for PDF files that have already been misidentified because the erroneous `fileClass : "audio"` attribute appears to be getting saved in the document. This causes future runs by the robot to skip the identification step.

**Comment by ahayes** [comment]
This may have been resolved by @sruest in work related to #912 .
I will need to double-check.
